---
driver:
  name: vagrant

driver_config:
  network:
    - ["forwarded_port", {guest: 80, host: 8080}]
    - ["forwarded_port", {guest: 3780, host: 3780}]
    - ["private_network", {ip: "192.168.33.33"}]
  customize:
    memory: 2024
    cpus: 2

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04

suites:
  - name: default
    run_list:
      - recipe[nexpose::default]
    attributes:
