---
driver:
  name: docker

driver_config:
  forward:
    - 8080:8080
    - 3780:3780

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04

suites:
  - name: default
    run_list:
      - recipe[nexpose::default]
    attributes:
